name: CI Blazor

on:
  push:
    branches:
      - master 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.407' 
    - name: Restaurar dependencias, construir y publicar la aplicación
      run: |
        dotnet restore
        dotnet build 
        dotnet publish --configuration Release --self-contained -r linux-x64 -o publish
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp publish/wwwroot/index.html publish/wwwroot/404.html
    - name: Publicar en GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./publish/wwwroot
